[profile.default]
src = 'contracts'
out = 'out'
test = 'tcast/test'
libs = ['node_modules', 'foundry/src']
gas_reports = ["*"]
optimizer = true
cache_path  = 'cache'
ffi = true
fs_permissions = [{ access = "write", path = "./"}]
[rpc_endpoints]
bsc_testnet = "${ARBITRUM_TEST_RPC_URL}"
